name: Build-Test-Deploy

on:
  push:
    -main
jobs: 
  Build-Job:
    runs-on: ubuntu-latest
    name: Making builds
    steps:
      - uses: actions/checkout@av1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge

